version: '3.4'

services:
  fakerapi:
    image: faker
    environment:
      - dotnet=Development
    build:
      context: .
      dockerfile: Faker.Api/Dockerfile
    restart: on-failure
    ports:
      - "1226:80"